# Generated by Django 4.2.7 on 2023-11-24 23:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meals_and_dishes', '0002_mealsanddishes_is_ready'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=255)),
                ('amount', models.IntegerField(default=0)),
                ('table_no', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('MPESA', 'M-Pesa')], default='CASH', max_length=10)),
                ('meals_and_dishes', models.ManyToManyField(to='meals_and_dishes.mealsanddishes')),
            ],
        ),
    ]
