# Generated by Django 4.2.7 on 2024-02-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('receiptNumber', models.CharField(max_length=150)),
                ('balance', models.IntegerField()),
                ('transactionDate', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=255)),
            ],
        ),
    ]
