# Generated by Django 4.2.7 on 2024-02-28 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_alter_orderitem_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('receiptNumber', models.CharField(max_length=150)),
                ('balance', models.IntegerField()),
                ('transactionDate', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=255)),
                ('fullName', models.CharField(blank=True, max_length=150, null=True)),
                ('order_id', models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
