# Generated by Django 4.2.7 on 2023-11-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealsAndDishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=255)),
                ('qty', models.IntegerField(default=1)),
                ('media_url', models.CharField(default='https://thumbs2.imgbox.com/3f/24/TGdwPRoe_t.jpeg', max_length=255)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
