# Generated by Django 4.2.7 on 2023-11-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restauranttable',
            name='id',
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='table_no',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
