# Generated by Django 4.2.7 on 2023-11-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_remove_restauranttable_id_restauranttable_table_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauranttable',
            name='qr_code',
            field=models.TextField(),
        ),
    ]
