# Generated by Django 4.2.7 on 2023-11-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals_and_dishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealsanddishes',
            name='is_ready',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
