# Generated by Django 4.2.7 on 2023-12-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals_and_dishes', '0004_alter_mealsanddishes_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealsanddishes',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
