# Generated by Django 4.2.7 on 2023-12-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals_and_dishes', '0005_mealsanddishes_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealsanddishes',
            name='quantity',
        ),
    ]
